[Translation] tutorial/part-three
gatsbyjs/gatsby-vi pull request #11
Opened 2019-12-19 19:11 UTC by dennis-IT

Complete the translation for tutorial-part 3

2019-12-22 05:03 UTC, vitokhangnguyen requested changes
Chào anh, em đã đọc qua và có một số review, anh xem qua giúp em nhá!
Có gì không hiểu hay không đồng ý, anh cứ nói em.

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +title: Tạo Nested Layout Components
Tựa đề anh dịch là "Tạo những Component Bố cục Lồng nhau" giúp em nhá.

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +## Có gì trong bài hướng dẫn này?
Em thấy chỗ này dịch là "Bài hướng dẫn này có những gì?" nghe thuận tai hơn

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Ở phần này, bạn sẽ học về các thành phần mở rộng của Gatsby và tạo các thành phần "bố cục".
Từ "plugins" anh giữ nguyên bản tiếng Anh giúp em nhá (technical term).
Cả từ "component" nữa (technical term trong React).
Anh sửa 2 từ này lại nều cần trong phần còn lại trong bài luôn nhá.

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Các thành phần mở rộng của Gatsby là những gói JavaScript nhằm bổ sung chức năng cho một trang web trên nền tảng Gatsby. Gatsby được thiết kế với khả năng nâng cấp, tức là các thành phần này có thể m
Gatsby site -> trang web Gatsby. Cụm này đã được lặp nhiều lần trong các phần trước nên dịch đơn giản vậy là được rồi nha anh.
is designed to be extensible -> được thiết kế để có thể mở rộng
plugins are able to extend and modify just about everything Gatsby does -> các plugin có thể mở rộng và chỉnh sửa hầu như mọi thứ mà Gatsby thực hiện

(em đang cố gắng tránh từ "thành phần" vì nó gây quán hiều hiểu lầm với các term như plugin, component vì đây đều là các technical terms)

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Các thành phần bố cục được dùng cho từng khu vực của website mà bạn muốn chia sẻ giữa nhiều trang với nhau. Ví dụ, các websites thường sẽ có cùng có một thành phần bố cục ở đầu trang và cuối trang. M
section (in this context) -> bộ phận
a layout component with a shared header and footer -> một component bố cục ở đầu trang và cuối trang được dùng chung (trong nhiều trang khác nhau). Anh chú thích thêm phần trong ngoặc để tránh hiểu nhầm nhá.
Other common things to add to layouts are a sidebar and/or navigation menu -> Những thứ thông thường khác cũngđược thêm vào bố là sidebar và/hoặc menu định hướng.
On this page for example -> Ví dụ như ở trnag này

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Cùng tìm hiểu sâu hơn về phần 3.
Let's... -> Hãy...

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Có lẽ bạn đã quen thuộc với ý tưởng của các thành phần mở rộng. Nhiều hệ thống phần mềm hỗ trợ việc thêm vào các thành phần mở rộng được tùy chỉnh để bổ sung các chức năng mới hoặc thay đổi các hoạt
custom plugins -> các plugin tùy chỉnh
or even -> hoặc thậm chí
core -> cốt lõi

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Những thành viên cộng đồng (tương tự như bạn!) có thể đóng góp các thành phần mở rộng (các đoạn code nhỏ được viết bằng JavaScript) để những người khác có thể sử dụng khi xây dựng các trang web trên
small amounts of JavaScript code -> các đoạn code JavaScript nhỏ (Em muốn rút gọn nó tí thôi)
Gatsby sites -> những trang web Gatsby

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +> Đã có hàng trăm plugins rồi! Tìm hiểu thêm về Gatsby [Thư viện Plugin](/plugins/).
Anh uncapitalize "T" trong "Thư viện Plugin" với thêm phía sau "của Gatsby" giúp em.

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Mục đích của chúng tôi là làm cho các thành phần mở rộng dễ dàng cài đặt và sử dụng. Bạn sẽ có thể sử dụng các thành phần mở rộng này trong hầu hết các trang web trên nền tảng Gatsby mà bạn xây dựng.
You will likely be using plugins in almost every Gatsby site you build
-> Bạn rất có khả năng là sẽ sử dụng plugin trong hầu hết mọi trang web Gatsby mà bạn xây dựng

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Trong phần giới thiệu về sử dụng các thành phần mở rộng, chúng ta sẽ cài đặt và sử dụng chúng cho Typography.js.
implement -> triển khai

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +[Typography.js](https://kyleamathews.github.io/typography.js/) là một thư viện JavaScript nhằm tạo ra các kiểu mẵu toàn cục về thiết kế chữ cho trang web của bạn. Thư viện này có một [Gatsby plugin](
which -> mà sẽ
styles -> các định dạng
corresponding Gatsby plugin -> plugin Gatsby tương ứng

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Như chúng ta đã đề cập ở [phần 2](/tutorial/part-two/), ngay lúc này bạn nên đóng tất cả các cửa sổ terminal và các tập tin projects ở những phần trước của bài hướng dẫn. Sau đó mở một của sổ termina
project -> dự án
to keep things clean on your desktop -> để giữ mọi thứ gọn gàng trên Desktop
move -> di chuyển

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +### ✋ Cài đặt và tùy chỉnh `gatsby-plugin-typography`
configure -> cấu hình

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Có 2 bước chính để sử dụng một thành phần mở rộng: Cài đặt và tùy chỉnh.
configure -> cấu hình

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +1. Cài đặt `gatsby-plugin-typography` NPM package.
Cài đặt gói NPM cho gatsby-plugin-typography

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +> Chú ý: Typography.js yêu cầu thêm một số tệp khác đã được bao gồm trong phần hướng dẫn. Các yêu cầu thêm tương tự như vậy sẽ được nêu rõ trong phần hướng dẫn "cài đặt" của mỗi thành phần mở rộng.
additional packages -> gói bổ sung
Additional requirements -> yêu cầu bổ sung

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +2. Chỉnh sửa file `gatsby-config.js` tại thư mục gốc của project thành:
project -> dự án
to the following (in this context) -> như sau

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +`gatsby-config.js` là một file đặc biệt khác mà Gatsby sẽ tự động nhận diện. Đây là nơi bạn sẽ thêm các thành phần mở rộng và những tùy chỉnh khác của trang web.
configuration -> cấu hình

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +> Truy cập [doc on gatsby-config.js](/docs/gatsby-config/) để tìm hiểu thêm, nếu bạn muốn.
Check out -> Xem qua
doc on gatsby-config.js -> tài liệu về gatsby-config.js

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +3. Typography.js cần một file tùy chỉnh. Tạo một thư mục mới đặt tên `utils` trong thư mục `src`. Sau đó thêm vào `utils` một file mới đặt tên `typography.js` và sao chép đoạn sau vào trong file:
configuration file -> tập tin cấu hình

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +4. Khởi động development server.
development server -> máy chủ phát triển

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Sau khi bạn tải trang web, nếu bạn dùng công cụ Chrome developer để kiểm tra HTML được tạo ra, bạn sẽ thấy rằng thành phần mở rộng trong việc thiết kế chữ đã thêm một `<style>` element vào `<head>` e
Once -> một khi
if you inspect the generated HTML using the Chrome developer tools -> Nếu bạn kiểm tra qua HTML được tạo ra, bằng cách sử dụng Chrome Developer Tools
typography plugin -> plugin định dạng
element -> phần tử

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +### ✋ Thay đổi nội dung và kiểu mẫu
Make some content and style changes -> Thực hiện một số thay đổi nội dung và định dạng

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +sự thay đổi trên CSS được tạo ra bởi Typography.js dễ dàng hơn.
effect -> hiệu ứng

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Cùng hoàn thiện nhanh nào. Nhiều trang web có một cột đơn văn bản được canh lề ở giữa trang. Để làm được điều này, thêm đoạn sau vào
Let's make a quick improvement -> Cùng thực hiện một sự cải thiện nhanh nào!

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Tốt lắm. Bạn đã cài đặt và tùy chỉnh xong thành phần mở rộng Gatsby đầu tiên!
configure -> cấu hình

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Bây giờ chúng ta học tiếp về các các thành phần bố cục. Để chuẩn bị cho phần này, hãy thêm một vài trang mới vào trong project của bạn bao gồm: một trang about và một trang contact.
project -> dự án

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Trang about mới sẽ trông như thế này:
Let's see what the new about page looks like -> Hãy cùng xem trang about mới trông như thế nào

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Hmm. Sẽ tốt hơn nếu nội dung của hai trang mới được canh lề ở giữa tương tự như trang index. Và sẽ tốt hơn nếu có sự điều hướng toàn cục để khách dễ dàng hơn trong việc tìm kiếm và truy cập các trang
And it would be nice to have some sort of global navigation so it's easy for visitors to find and visit each of the sub-pages
-> Và sẽ hay hơn nếu nó có một cách để điều hướng trong toàn bộ trang web để nó trở nên dễ dàng cho những người ghé thăm trang web có thể tìm và truy cập các trang phụ.

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Bạn sẽ thực hiện các sự thay đổi này thông qua thành phần bố cục đầu tiên.
by creating your first layout component
-> bằng cách tạo ra component bố cục đầu tiên

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +3. Nạp thành phần bố cục mới này vào trong `src/pages/index.js` ở trang web của bạn:
import -> nhúng
page component -> component trang

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Tốt lắm, bố cục đã xong! Nội dung trang index của bạn vẫn được canh lề ở giữa.
is working -> đã hoạt động

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +4. Nạp thành phần bố cục vào trong `about.js` và `contact.js` (tương tự như bạn đã làm cho `index.js` ở bước trước đó).
import -> nhúng

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Nội dung tất cả ba trang của bạn đã được canh lề ở giữa bằng cách sử dụng chung một thành phần bố cục!
all of three of your pages -> cả 3 trang cả bạn
thanks to this single shared layout component -> nhờ component bố cục dùng chung duy nhất này

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +### ✋ Thêm vào đường dẫn điều hướng giữa các trang
Add navigation links between pages
-> Thêm liên kết điều hướng giữa các trang

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Và bạn đã hoàn thành xong! Một site gồm 3 trang với điều hướng toàn cục cơ bản.
site -> trang web

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +_Thử thách:_ Với sức mạnh của "thành phần bố cục" mới, hãy thử thêm vào đầu trang, cuối trang, điều hướng toàn cục, thanh bên,... vào trang web của bạn trên nền tảng Gatsby!
sidebar -> từ này giữ nguyên giúp em nhá
Gatsvy site -> trang web Gatsby

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +## Có gì ở phần kế tiếp?
What's coming next? -> Tiếp theo là gì?

2019-12-22 05:03 UTC, vitokhangnguyen commented on docs/tutorial/part-three/index.md
> +Tiếp tục [phần 4 của bài hướng dẫn](/tutorial/part-four/) để học thêm về lớp dữ liệu của Gatsby và tạo trang một cách hệ thống.
programmatically -> bằng cách lập trình

2019-12-23 16:56 UTC, dennis-IT commented
Hi Khang, a update file rồi. E check lại xem còn cần sửa gì nữa không. Thanks e comment nhé. Rất kĩ. 👍 :)

2019-12-27 06:11 UTC, vitokhangnguyen approved these changes

2019-12-27 06:13 UTC, vitokhangnguyen commented
Chào anh! Em có polish lại tí trước khi approve rồi merge nha. Cám ơn anh vì đã dành thời gian đóng góp.

Merry Chrismtas and Happy New Year!

2019-12-27 06:13 UTC, merged