`[Translation] tutorial/part-two`
gatsbyjs/gatsby-vi pull request #12
Opened 2019-12-19 21:32 UTC by tonyvugithub

I could not find a good equivalence of the word "plugin" in Vietnamese so i decided to opt for keeping it untranslated. I believe in a few cases you might have to do that to prevent readers from confusion.

2019-12-20 23:02 UTC, vitokhangnguyen requested changes
Anh xem qua rồi chỉnh sửa nếu cần thiết giúp em nhá!
Có gì anh thấy không phù hợp cứ nói em.

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
>  -->
Có 1 đoạn markup ở đầu document...
```
---
title: Introduction to Styling in Gatsby
typora-copy-images-to: ./
disableTableOfContents: true
---
```
anh dịch giúp em cái title thành `Giới thiệu về cách sử dụng CSS trong Gatsby` luôn nhá

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Trong phần này, các bạn sẽ được tìm hiểu về những tùy chọn trong thiết kế các trang web trên nền tảng Gatsby và hiểu sâu hơn về sử dụng các thành phần của React trong việc xây dựng các trang web.
options (in this context) -> lựa chọn
styling -> tạo kiểu (từ này em định sẽ standardize vô glossary luôn nện anh fix giúp em). Anh sửa lại cho toàn bộ document luôn nhá.
React components -> cụm này anh giữ nguyên giúp em vì components là 1 technical term trong React. Anh sửa lại cho toàn bộ document luôn nhá.
for -> nhằm

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Mỗi trang web đều có một phong cách toàn cục. Chúng bao gồm những đặc điểm như kiểu chữ và tông màu nền. Các phong cách này cho cái nhìn tổng thể về trang web - giống như là màu và kết cấu của một bứ
set (in this context) -> đặt ra

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +## Sử dụng các phong cách toàn cục
global style -> tạo kiểu toàn cục

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +### Tạo các phong cách toàn cục với các tập tin CSS kiểu mẫu
standard -> tiêu chuẩn

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Một trong những cách trực tiếp nhất để thêm phong cách toàn cục là sử dụng một bản định kiểu `.css` toàn cục
straightforward -> tường minh
stylesheet -> phía sau "bản định kiểu" này, anh chú thích trong ngoặc đơn (stylesheete) giúp em nhá. Anh chỉ cần chú thích 1 lần tại đây thôi.

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +#### ✋ Tạo một trang web mới tích hợp Gatsby
Gatsby site -> trang web Gatsby

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Bắt đầu bằng việc tạo một trang web trên nền tảng Gatsby. Cách tốt nhất (đặc biệt nếu bạn chưa quen với sử dụng dòng lệnh) là đóng cửa sổ terminal bạn đã sử dụng cho [phần một](/tutorial/part-one/) v
Gatsby site -> trang web Gatsby

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Mở một cửa sổ terminal mới, tạo một trang web mới trên nền tảng Gatsby gọi là "hello world" , và chạy máy chủ dành cho phát triển:
new "hello world" gatsby site -> trang web Gatbsy "hello world" mới (cụm này đã được đề cập ở các phần trước nên dịch ngắn gọn vầy là được ạ)
...và a xóa dấu space đằng trước comma "," giúp em nhá

development server -> máy chủ phát triển

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Bây giờ bạn đã có một trang web mới trên nền tảng Gatsby(dựa trên các tập tin trong kho thư mục Gatsby "hello world" starter) với cấu trúc như sau:
Gatsby site -> trang web Gatsby
...anh add 1 dấu space đằng trước open-bracket "(" giúp em nhá
based on the Gatsby "hello world" starter -> dựa trên mẫu khởi động Gatsby "hello world"

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +> Chú ý: Bạn có thể chủ động tạo các thư mục và tập tin này bằng chương trình biên tập mã nguồn của bạn nếu thấy phù hợp hơn.
feel free -> thoải mái
code editor -> trình soạn thảo code (trong quá trình dịch, em nghĩ mình nên giữ nguyên từ code vì nó khá thông dụng) 
prefer -> muốn

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +2. Định nghĩa một vài phong cách trong tập tin `global.css`:
styles -> định dạng (styling anh vẫn dịch là tạo kiểu nhá)

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +> Chú ý: Vị trí đặt tập tin css bên trong thư mục `/src/styles/` là tùy ý của bạn.
example css file -> tập tin css mẫu

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +#### ✋ Bao gồm bản định kiểu trong `gatsby-browser.js`
include (in this context) -> nhúng ... vào trong ...

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +> 💡 Vậy `gatsby-browser.js` là gì? Bạn không cần phải quan tâm về nó quá nhiều bây giờ, bạn chỉ cần biết `gatsby-browser.js` là một trong số ít những tập tin đặc biệt mà Gatsby tìm và sử dụng (nếu có
the docs -> tài liệu này

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +3. Chạy máy chủ dành cho phát triển:
development server -> máy chủ phát triển

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Nếu bạn quan sát dự án của bạn trên trình duyệt, bạn có thể thấy màu tím Lavender được áp dụng cho "hello world" starter:
"hello world" starter -> mẫu khởi động "hello world"

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +> Thông tin thêm: Mục này của hướng dẫn tập trung vào cách nhanh nhất và trực tiếp nhất để bắt đầu thiết kế một trang web trên nền tảng Gatsby — nhập các tập tin CSS kiểu mẫu một cách trực tiếp, thôn
Gatsby site -> trang web Gatsby
standard -> tiêu chuẩn
shared layout components -> những component bố cục dùng chung
Check out the docs -> tham khảo tài liệu
that approach -> cách thức đó

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +## Sử dụng CSS trong phạm vi của thành phần
...trong phạm vi component

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Cho đến nay, chúng ta đã bàn về phương pháp tiếp cận truyền thống về việc sử dụng những bản định mẫu css tiêu chuẩn. Bây giờ, chúng ta sẽ bàn về những phương pháp đa dạng về mô dun hóa CSS để giải qu
modularizing -> mô-đun hóa
to tackle styling in a component-oriented way -> giải quyết vấn đề tạo kiểu nằng cách định hướng theo component

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +### Những CSS Mô dun
Cụm này nên giữ nguyên "CSS Modules" vì nó là tên của 1 tool

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +> Một **CSS Module** là một tập tin mà ở đó tất cả các tên gọi thứ lớp và hiệu ứng.
CSS file -> tập tin CSS
class -> từ này em nghĩ nên giữ nguyên vì nó là technical term

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +> được mặc định giới hạn trong phạm vi giới hạn.
locally -> ...trong phạm vi cục bộ

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Những mô dun CSS rất phổ biến vì chúng cho phép bạn viết CSS như bình thường nhưng an toàn hơn. Công cụ sẽ tự động tạo ra tên gọi độc nhất dành cho thứ lớp và hiệu ứng, cho nên bạn không cần phải lo
"CSS Modules" ở đây nên giữ nguyên vì nó là tên của 1 tool
class -> từ này em nghĩ nên giữ nguyên vì nó là technical term

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Với những CSS mô dun này, Gatsby có thể được sử dụng ngay lập tức. Phương pháp này được khuyến nghị sử dụng cho những ai mới bắt đầu phát triển trên nền tảng Gatsby nói riêng(cũng như là React nói ch
"CSS Modules" ở đây nên giữ nguyên vì nó là tên của 1 tool
Anh add 1 dấu space vào phía trước "(" giúp em nhá.

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +#### ✋ Xây dựng một trang web mới sử dụng Mô dun CSS
"CSS Modules" ở đây nên giữ nguyên vì nó là tên của 1 tool

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Bạn sẽ thấy rằng bạn đã nhập một tập tin mô dun css tên là `container.module.css`. Cùng tạo tập tin đó nào.
css module -> mô-đun css

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Bạn sẽ thấy rằng tên của tập tin kết thúc với `.module.css` thay vì thường là `.css`. Đây là cách để bạn cho Gatsby biết rằng tập tin CSS này nên được xử lý như là một mô dun CSS thay vì là một tập t
CSS module -> mô-đun CSS

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
>  ![Page with CSS module styles](css-modules-basic.png)
Anh dịch cái alt-text cho cái image giúp em luôn nhá

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +#### ✋ Thiết kế một thành phần sử dụng mô dun CSS
Style a component using CSS Modules -> Tạo kiểu cho một component sử dụng CSS Modules

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Trong mục này, bạn sẽ tạo một danh sách về người với tên gọi, ảnh đại diện, và tiểu sử cá nhân trích ngang. Bạn sẽ tạo một thành phần tên là `<User />` và thiết kế thành phần này sử dụng mô dun CSS.
component và CSS Modules anh giữ nguyên từ giúp em nhá.

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Mã lệnh `console.log(styles)` sẽ ghi chú kết quả của việc nhập tập tin để bạn có thể thấy kết quả đã thay đổi trong tập tin `./about-css-modules.module.css`. Nếu bạn mở bảng điều khiển của nhà lập tr
log (in this context) -> in
processed -> đã qua xử lý
using e.g. Firefox or Chrome's developer tools -> sử dụng developer tools của Firefox hoặc là Chrome

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
>  ![Import result of CSS module in console](css-modules-console.png)
Anh dịch cái alt-text của cái image giúp em luôn nhá

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Nếu bạn so sánh với tập tin CSS của mình, bạn sẽ thấy mỗi thứ lớp bây giờ là một chìa khóa bên trong đối tượng được nhập và mỗi mỗi chỉ đến một chuỗi kí tự dài. Ví dụ `avatar` chỉ đến `src-pages----a
class -> từ này em nghĩ nên giữ nguyên
key -> em nghĩ nên dịch là "trường" (field)
These are the class names CSS Modules generates -> Những trường này là nhựng tên class mà CSS Modules tạo ra.

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +4. Tạo một thành phần mới gọi là `<User />` tạo trong dòng với thành phần trang trong `about-css-modules.js`. Điều chỉnh `about-css-modules.js` sao cho giống như sau:
4. Create a new `<User />` component inline in the `about-css-modules.js` page.
-> 4. Tạo một component mới gọi là `<User />` "inline" (trong cùng 1 file) trong trang `about-css-modules.js`.
Cụm inline component nên giữ nguyên vì nó là 1 technical term trong React

Ngay trước chữ "Điều chính", anh add một newline tại đây cho đãm bảo match dòng với bản gốc nhá.

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +> Thông tin thêm: Nhìn chung, Nếu bạn sử dụng một thành phần ở nhiều vị trí khác nhau trên cùng một trang, thành phần đó cần phải có tập tin mô dun của riêng nó bên trong thư mục `components`. Tuy nh
Uncapitalize từ "Nếu" sau comma ",".

Câu này có nghĩa là... Nếu 1 component được sử dụng ở nhiều nơi khác nhau trong cùng một **trang web** (ý là cả 1 dự án), nó nên được đặt thành 1 mơ-đun riêng trong thư mục "components". Nhưng nếu nó chỉ được sử dụng trong 1 file duy nhất, hãy tạo nó "inline".

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Trang kết quả cuối cùng cần giống như sau:
should -> nên

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
>  ![User list page with CSS modules](css-modules-userlist.png)
Anh dịch cái alt-text trong image giúp em luôn nhá

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +CSS-in-JS là một kiểu thiết kế định hướng theo thành phần. Phần đông, nó là một kiểu mẫu mà ở đó [CSS được viết cùng dòng bằng cách sử dụng JavaScript](https://reactjs.org/docs/faq-styling.html#what-
CSS-in-JS is a component-oriented styling approach.
-> CSS-in-JS là một cách tạo kiểu định hướng theo component.

Từ inline anh giữ nguyên giúp em nhá

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Có rất nhiều thư viện CSS-in-JS và nhiều trong số chúng đã có plugins của Gatsby. Chúng ta sẽ không bàn về một ví dụ của CSS-in-JS trong phần hướng dẫn này, tuy nhiên chúng tôi khuyến khích bạn tìm h
Anh bỏ từ tìm hiểu bên ngoài và thay từ explore trong [...] thành tìm hiểu nhá
ecosystem -> hệ sinh thái

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +Nếu bạn muốn tìm hiểu thêm, hãy xem [Christopher "vjeux" Chedeau's 2014 presentation that sparked this movement](https://speakerdeck.com/vjeux/react-css-in-js) và [Mark Dalgleish's more recent post "
Anh dịch giúp em 2 cái trong [...] luôn nhá

2019-12-20 23:02 UTC, vitokhangnguyen commented on docs/tutorial/part-two/index.md
> +### những lựa chọn CSS khác
Capitalize đầu câu giúp em nhá

2019-12-21 01:00 UTC, tonyvugithub commented
-> Note: The placement of the example css file in a `/src/styles/`
folder is arbitrary.

+> Chú ý: Vị trí đặt tập tin css bên trong thư mục `/src/styles/` là
tùy ý của bạn.

cái này a dịch lại là

*Chú ý: Vị trí đặt tập tin css của ví dụ bên trong thư mục
`/src/styles/` là tùy ý của bạn.*

*--------------------------------------*


#### ✋ Include the stylesheet in `gatsby-browser.js`

+#### ✋ Tích hợp bản định kiểu trong `gatsby-browser.js`


include (in this context) -> nhúng ... vào trong ...
cái này a dịch lại là Tích hợp...vào. Vì khi mình include một cái gì đó vào
một cái gì đó tức mình tích hợp nó vào chung 1 structure với cái còn lại.
(Hợp lại với nhau)


On Fri, Dec 20, 2019 at 6:02 PM Khang Nguyen <notifications@github.com>
wrote:

> *@vitokhangnguyen* requested changes on this pull request.
>
> Anh xem qua rồi chỉnh sửa nếu cần thiết giúp em nhá!
> Có gì anh thấy không phù hợp cứ nói em.
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360563278>:
>
> > @@ -14,32 +14,32 @@ disableTableOfContents: true
>
>
>
>  -->
>
>
> Có 1 đoạn markup ở đầu document...
>
> ---
>
> title: Introduction to Styling in Gatsby
>
> typora-copy-images-to: ./
>
> disableTableOfContents: true
>
> ---
>
>
> anh dịch giúp em cái title thành Giới thiệu về cách sử dụng CSS trong
> Gatsby luôn nhá
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360565231>:
>
> >
>
> -In this part, you're going to explore options for styling Gatsby websites and dive deeper into using React components for building sites.
>
> +Trong phần này, các bạn sẽ được tìm hiểu về những tùy chọn trong thiết kế các trang web trên nền tảng Gatsby và hiểu sâu hơn về sử dụng các thành phần của React trong việc xây dựng các trang web.
>
>
> options (in this context) -> lựa chọn
> styling -> tạo kiểu (từ này em định sẽ standardize vô glossary luôn nện
> anh fix giúp em). Anh sửa lại cho toàn bộ document luôn nhá.
> React components -> cụm này anh giữ nguyên giúp em vì components là 1
> technical term trong React. Anh sửa lại cho toàn bộ document luôn nhá.
> for -> nhằm
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360566027>:
>
> >
>
> -Every site has some sort of global style. This includes things like the site's typography and background colors. These styles set the overall feel of the site — much like the color and texture of a wall sets the overall feel of a room.
>
> +Mỗi trang web đều có một phong cách toàn cục. Chúng bao gồm những đặc điểm như kiểu chữ và tông màu nền. Các phong cách này cho cái nhìn tổng thể về trang web - giống như là màu và kết cấu của một bức tường cho cái nhìn tổng thể về một căn phòng.
>
>
> set (in this context) -> đặt ra
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360566510>:
>
> >
>
> -## Using global styles
>
> +## Sử dụng các phong cách toàn cục
>
>
> global style -> tạo kiểu toàn cục
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360566877>:
>
> >
>
> -### Creating global styles with standard CSS files
>
> +### Tạo các phong cách toàn cục với các tập tin CSS kiểu mẫu
>
>
> standard -> tiêu chuẩn
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360568319>:
>
> >
>
> -One of the most straightforward ways to add global styles to a site is using a global `.css` stylesheet.
>
> +Một trong những cách trực tiếp nhất để thêm phong cách toàn cục là sử dụng một bản định kiểu `.css` toàn cục
>
>
> straightforward -> tường minh
> stylesheet -> phía sau "bản định kiểu" này, anh chú thích trong ngoặc đơn
> (stylesheete) giúp em nhá. Anh chỉ cần chú thích 1 lần tại đây thôi.
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360568888>:
>
> >
>
> -#### ✋ Create a new Gatsby site
>
> +#### ✋ Tạo một trang web mới tích hợp Gatsby
>
>
> Gatsby site -> trang web Gatsby
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360570401>:
>
> >
>
> -Start by creating a new Gatsby site. It may be best (especially if you're new to the command line) to close the terminal windows you used for [part one](/tutorial/part-one/) and start a new terminal session for part two.
>
> +Bắt đầu bằng việc tạo một trang web trên nền tảng Gatsby. Cách tốt nhất (đặc biệt nếu bạn chưa quen với sử dụng dòng lệnh) là đóng cửa sổ terminal bạn đã sử dụng cho [phần một](/tutorial/part-one/) và mở một cửa sổ terminal mới cho phần hai.
>
>
> Gatsby site -> trang web Gatsby
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360572393>:
>
> >
>
> -Open a new terminal window, create a new "hello world" gatsby site, and start the development server:
>
> +Mở một cửa sổ terminal mới, tạo một trang web mới trên nền tảng Gatsby gọi là "hello world" , và chạy máy chủ dành cho phát triển:
>
>
> new "hello world" gatsby site -> trang web Gatbsy "hello world" mới (cụm
> này đã được đề cập ở các phần trước nên dịch ngắn gọn vầy là được ạ)
> ...và a xóa dấu space đằng trước comma "," giúp em nhá
>
> development server -> máy chủ phát triển
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360573661>:
>
> >
>
>  ```shell
>
>  gatsby new tutorial-part-two https://github.com/gatsbyjs/gatsby-starter-hello-world
>
>  cd tutorial-part-two
>
>  ```
>
>
>
> -You now have a new Gatsby site (based on the Gatsby "hello world" starter) with the following structure:
>
> +Bây giờ bạn đã có một trang web mới trên nền tảng Gatsby(dựa trên các tập tin trong kho thư mục Gatsby "hello world" starter) với cấu trúc như sau:
>
>
> Gatsby site -> trang web Gatsby
> ...anh add 1 dấu space đằng trước open-bracket "(" giúp em nhá
> based on the Gatsby "hello world" starter -> dựa trên mẫu khởi động Gatsby
> "hello world"
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360574811>:
>
> > @@ -59,9 +59,9 @@ cd styles
>
>  touch global.css
>
>  ```
>
>
>
> -> Note: Feel free to create these directories and files using your code editor, if you'd prefer.
>
> +> Chú ý: Bạn có thể chủ động tạo các thư mục và tập tin này bằng chương trình biên tập mã nguồn của bạn nếu thấy phù hợp hơn.
>
>
> feel free -> thoải mái
> code editor -> trình soạn thảo code (trong quá trình dịch, em nghĩ mình
> nên giữ nguyên từ code vì nó khá thông dụng)
> prefer -> muốn
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360575293>:
>
> > @@ -72,26 +72,26 @@ You should now have a structure like this:
>
>  │       └── global.css
>
>  ```
>
>
>
> -2. Define some styles in the `global.css` file:
>
> +2. Định nghĩa một vài phong cách trong tập tin `global.css`:
>
>
> styles -> định dạng (styling anh vẫn dịch là tạo kiểu nhá)
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gatsby-vi/pull/12#discussion_r360575933>:
>
> >
>
>  ```css:title=src/styles/global.css
>
>  html {
>
>    background-color: lavenderblush;
>
>  }
>
>  ```
>
>
>
> -> Note: The placement of the example css file in a `/src/styles/` folder is arbitrary.
>
> +> Chú ý: Vị trí đặt tập tin css bên trong thư mục `/src/styles/` là tùy ý của bạn.
>
>
> example css file -> tập tin css mẫu
> ------------------------------
>
> In docs/tutorial/part-two/index.md
> <https://github.com/gatsbyjs/gats [...]

2019-12-21 04:16 UTC, vitokhangnguyen approved these changes

2019-12-21 04:17 UTC, vitokhangnguyen commented
Hi anh, em có chỉnh sửa 1 tí nữa về cách dùng từ với 1-2 cái typos (2 cái trên anh đề cập em không có chỉnh sửa).
Cám ơn anh đã dành thời gian đóng góp!

2019-12-21 04:17 UTC, merged