translated
gatsbyjs/gatsby-vi pull request #6
Opened 2019-11-26 21:29 UTC by nguyenami

Translation for code of conduct page

2019-11-27 03:50 UTC, vitokhangnguyen requested changes
Chào bạn @nguyenami, cám cơn vì sự đóng góp nhiệt tình của bạn. Mình có 1 số góp ý cho bài dịch của bạn. Bạn xem phía dưới giúp mình.

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Vì lợi ích của việc thúc đẩy một môi trường cởi mở và chào đón, chúng tôi với tư cách là người đóng góp và duy trì nền tảng cam kết mang đến cho mọi người tham gia vào dự án và cộng đồng của chúng tô
Một số từ mình nghĩ nên dịch gần nghĩa với bài gốc hơn:

1. maintainer: người bảo trì
1. a harassment-free experience for everyone, regardless of...: một môi trường không có sự quấy rối cho mọi người, bất kể...
1. gender identity and expression: bản sắc và biểu hiện về giới tính
1. sexual identity and orientation: bản sắc và định hướng về tình dục

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +- Tôn trọng các quan điểm và kinh nghiệm khác nhau
1. experiences (ở trong ngữ cảnh này) = trải nghiệm

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Người duy trì dự án có nhiệm vụ nêu rõ mức tiêu chuẩn của hành vi của nhóm và thực thi một cách minh khai, công bằng và hợp lý cho những hành vi không đủ tiêu chuẩn.
Mình nghĩ câu này nên dịch lại thế này:

"Người bảo trì dự án có nhiệm vụ nêu rõ mức tiêu chuẩn của những hành vi chấp nhận được và được kỳ vọng rằng họ sẽ thực hiện những hành động sửa chữa phù hợp và công bằng nhầm đáp lại những hành vi không được chấp nhận."

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Người duy trì dự án có quyền và nghĩa vụ để xoá, sửa và không đồng ý các lời bình luận, commits, code, sửa wiki, issues, và các đóng góp khác mà không theo đủ tiêu chuẩn, và có thể tạm thời hoặc vĩnh
1. maintainers: những người bảo trì
1. reject: từ chối
1. align: tuân theo
1. or: hoặc
1. they deem unappropriate: được họ cho là không phù hợp
1. offensive: xúc phạm ('x' thay vì 's')

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Quy tắc ứng xử này áp dụng đối với cả trong không gian dự án và không gian công cộng khi cá nhân làm đại diện cho dự án hoặc cộng đồng. Ví dụ về đại diện cho một dự án hoặc một cộng đồng bao gồm việc
1. maintainers: người bảo trì

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +## Quyền Thực Thi
1. Enforcement = Sự thi hành

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Các trường hợp lạm dụng, quấy rối hoặc hành vi không thể chấp nhận được có thể được báo cáo bằng cách liên hệ với nhóm dự án tại [conduct@gatsbyjs.com](mailto:conduct@gatsbyjs.com). Tất cả các khiếu
1. confidentiality with regard to the reporter of an incident: tình bảo mật liên quan đến người báo cáo sự việc

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Những người duy trì dự án không có thiện chí tuân theo hoặc thực thi Bộ quy tắc ứng xử có thể phải đối mặt với những cách xử lí hậu quả mang tính tạm thời hoặc vĩnh viễn tùy theo quyết định của các t
1. repercussions: hậu quả

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Nếu sau nỗ lực để hòa giải vấn đề mà vẫn nhận được phản hồi về những bình luận tiêu cực hoặc quấy rối mang tính lặp đi lặp lại, nhóm Gatsby có quyền xóa ai đó khỏi kho lưu trữ GitHub và / hoặc chặn h
1. more than one team member: nhiều hơn 1 thành viên

2019-11-27 03:50 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +## Đóng Góp
Chỗ này mình nghĩ nên tạm dịch là "Trích dẫn"

2019-11-27 20:42 UTC, nguyenami commented
@vitokhangnguyen - Mình đã sửa những lỗi bạn chỉ. Lâu ngày không viết tiếng việt nên cũng chai :))

2019-11-27 21:57 UTC, vitokhangnguyen requested changes

2019-11-27 21:57 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Người bảo trì dự án có quyền và nghĩa vụ để xoá, sửa và từ chối các lời bình luận, commits, code, sửa wiki, issues, và các đóng góp khác mà không tuân theo với bộ quy tắc ứng xử này, hoặc có thể tạm
1. ban = cấm

2019-11-27 21:57 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +Người bảo trì dự án có nhiệm vụ nêu rõ mức tiêu chuẩn của những hành vi chấp nhận được và được kỳ vọng rằng họ sẽ thực hiện những hành động sửa chữa phù hợp và công bằng nhầm đáp lại những hành vi kh
nhầm => nhằm (sorry, mình cũng quên tiếng Việt)

2019-11-27 21:57 UTC, vitokhangnguyen commented on docs/contributing/code-of-conduct.md
> +## Sự thi hành
Chỗ này bạn sửa lại thành "Thi hành" thôi giúp mình. Sorry...

2019-11-27 21:59 UTC, vitokhangnguyen commented
> @vitokhangnguyen - Mình đã sửa những lỗi bạn chỉ. Lâu ngày không viết tiếng việt nên cũng chai :))

Không sao bạn, mình chai y chang bạn vậy :)) Mình có đề xuất 1 số sửa chữa nữa, bạn xem qua giúp mình,

2019-12-01 22:10 UTC, nguyenami commented
Cảm ơn vì đã chờ, mình sửa lại mấy điểm đó rồi. :D

2019-12-02 17:57 UTC, vitokhangnguyen approved these changes
Good job! Cám ơn bạn nhiều vì đã đóng góp.

2019-12-02 17:57 UTC, merged