[Translation] tutorial/part-one
gatsbyjs/gatsby-vi pull request #9
Opened 2019-12-17 02:24 UTC by giatuongtran9

2019-12-19 20:41 UTC, vitokhangnguyen requested changes

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +title: Làm quen với các thành phần trong Gatsby
Tiêu đề này mình có sửa thành "Làm quen với các thành phần cấu tạo của Gatsby" trong #8, bạn chỉnh lại cho giống giúp mình nhé.

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +Trong [**bài hướng dẫn phần 0**](/tutorial/part-zero/), bạn đã tạo một trang mới dựa trên mẫu khởi động "hello world" sử dụng những lệnh sau:
Bạn bỏ từ "những" giúp mình nhé. Bản gốc không có "s"

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +Khi tạo một trang Gatsby mới, bạn cần sử dụng những cấu trục lệnh sau để tạo một trang mới dựa trên bất kì mẫu khởi động Gatsby hiện có:
can -> có thể

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
>  gatsby new [SITE_DIRECTORY_NAME] [URL_OF_STARTER_GITHUB_REPO]
Dòng này bạn dịch 2 cái `[SITE_DIRECTORY_NAME]` với `[URL_OF_STARTER_GITHUB_REPO]` giúp mình nhé

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +Nếu bạn bỏ qua phần URL ở cuối, Gatsby sẽ tự động tạo một trang cho bạn dựa vào [**bản mẫu mặc định**](https://github.com/gatsbyjs/gatsby-starter-default). Đối với phần này của bài hướng dẫn, hãy gắn
You can learn more about [modifying starters](/docs/modifying-a-starter) in the docs.
-> Bạn có thể tìm hiểu thêm về [chỉnh sửa mẫu khởi động](/docs/modifying-a-starter) trong tài liệu.

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +Trong trình soạn thảo code của bạn, mở phần code được tạo bới trang "Hello World" và xem các thư mục và tệp khác nhau trong thư mục "hello-world". Nó sẽ trông như thế này:
file -> tập tin

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +![dự án Hello World trong VS Code](01-hello-world-vscode.png)
"Dự án" capitalize chữ "D" giúp mình nhé

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +_Lưu ý: Một lần nữa, Again, trình soạn thảo hiển thị ở đây là Visual Studio Code. Nếu bạn sử dụng một trình soạn thảo khác, nó sẽ trông hơi khác._
Hình như bạn quên chưa xóa từ "Again" thì phải...
the editor shown here -> trình soạt thảo **được** thể hiện ở đây
a little different -> hơi khác một chút

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +> 💡 Nếu như bạn đã dừng máy chủ phát triển sau khi chạy lệnh `gatsby develop` in the previous section, hãy khởi động nó lại bây giờ, đã đến lúc để thực hiện một số thay đổi cho trang hello-world!
in the previous section -> trong phần trước
thay vì sử dụng comma ',", bạn sử dụng hyphen "-" cho giống bản gốc nhá

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +Mở tệp tại `src/pages/index.js`.Phần code trong tệp này tạo ra một thành phần chứa một div và vài văn bản - thích hợp, “Hello world!”
file -> tập tin
some text -> vài dòng văn bản (trong context này mình thấy dịch như thế này dễ hiểu hơn)
appropraitely -> mình thấy trong bản TV, loại bỏ từ này ra luôn, nó không có ý nghĩa gì nhiều và đọc không được phù hợp lắm
Từ "component" ở đây bạn dùng nguyên bản tiếng ANh giúp mình, chú thích bên cạnh (cụm thành phần). Trong toàn bộ phần còn lại của document này bạn chỉ cần dùng tiếng Anh cho từ này là đủ. Sau này nếu có thay đổi mình sẽ tạo issue sau.

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +1.  Thay đổi văn bản "Hello World!" thành "Hello Gatsby!" và lưu tệp. Nếu các cửa sổ của bạn nằm cạnh nhau, bạn có thể thấy các thay đổi về code và nội dung được phản ánh gần như ngay lập tức trong t
file -> tập tin
text -> dòng chữ (trong context này mình thấy thế này hợp hơn)

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +> 💡 Gatsby sử dụng **hot reloading** để tăng tốc quá trình phát triển của bạn. Về cơ bản, khi bạn đang chạy máy chủ (server) phát triển Gatsbyto, các tệp của trang Gatsby được xem ở background - bất
Gatsbyto - typo?
"watched" -> được theo dõi
in the background -> ở phía hậu trường, chú thích thêm (background) giúp mình nhá
your changes just appear -> các thay đổi của bạn sẽ xuất hiện (dịch vậy cho thuận miệng vậy...)

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +2.  Bây giờ bạn có thể làm những thay đổi của bạn rõ hơn một chút. Hãy thử thay thế code trong tệp `src/pages/index.js` với code bên dưới và lưu lần nữa. Bạn sẽ thấy những thay đổi trong văn bản - mà
file -> tập tin

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +> 💡 Chúng tôi sẽ giới thiệu nhiều hơn về kiểu (styling) trong Gatsby trong [**phần 2**](/tutorial/part-two/) của bài hướng dẫn.
styling -> tạo kiểu (bạn giữ nguyên phần chú thích trong ngoặc nha)

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +3.  Xóa kiểu dáng kích thước phông chữ, thay văn bản "Hello Gatsby!" thành tiêu đề cấp một (h1), và thêm một đoạn văn (p) bên dưới tiêu đề.
font size styling -> tạo kiểu kích thước phông

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
>  import React from "react"
Phần code phía dưới, bạn dịch 2 dòng...
  {/* highlight-start */}	  {/* highlight-end*/}
giúp mình luôn nhé

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +_Nếu như bạn quen thuộc với React và JSX, bạn có thể thoải mái bỏ qua phần này._ Nếu như bạn chưa từng làm việc với bộ khung (framework) React trước đây, bạn có thể tự hỏi HTML làm gì trong một hàm J
import: từ này giữ nguyên giúp mình nha vì nó trùng với keyword của Js
called -> được gọi là

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +Xem xét nội dung ban đầu của tệp `src/pages/index.js`:
file -> tập tin

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +Bây giờ bạn có thể phát hiện ra việc sử dụng nhập khẩu `'react'`! Nhưng chờ đã, Bạn đang viết JSX, không phải thuần HTML và JavaScript. Làm cách nào mà trình duyệt đọc được? Câu trả lời ngắn ngọn là:
Bạn giữ import nguyên bản nhá
It doesn't -> Nó không đọc được
"các trang Gatsby..." -> Capitalize đầu câu giúp mình nhé

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +## Xây dựng với các thành phần
Bạn dùng nguyên từ component cho cả phần dưới giúp mình nhá

2019-12-19 20:41 UTC, vitokhangnguyen commented on docs/tutorial/part-one/index.md
> +Được định nghĩa rộng rãi, một thành phần là một khối hợp nhất (building block) cho trang của bạn;Nó là một đoạn mã khép kín mô tả một phần của UI (giao diện người dùng).
Bạn dịch câu này lại như thế này giúp mình nhá:
Broadly defined, a component is a building block for your site; It is a self-contained piece of code that describes a section of UI (user interface).
-> Được định nghĩa một cách rộng rãi, một component là một khối cấu tạo nên trang web của bạn; Nó là một đoạn code khép kín mô tả một phần của UI (user interface - giao diện người dùng).

2019-12-19 20:43 UTC, vitokhangnguyen commented
@giatuongtran9 Bạn sửa phần mình đã feedback giúp mình nhá. Với cách bạn dùng từ "component" cho phần con lại của document mình chưa feedback nữa. Sau đó mình sẽ review tiếp.

Nếu bạn không có thời gian thì cứ bảo mình, mình sẽ tiếp tục với phần bạn đã dịch và tự chỉnh sửa lại.

Cám ơn bạn vì đã dành thời gian dịch!

2019-12-21 02:39 UTC, giatuongtran9 commented
@vitokhangnguyen mình nghĩ tệp và tập tin giống nhau mà mình đã sửa lại hết thành tập tin rồi

2019-12-29 09:16 UTC, vitokhangnguyen commented
@giatuongtran9 
Mình vừa review và chỉnh sửa bản dịch của bạn 1 tí  (cdb299c90dacf1cd8acff2488785cda811ecf4d7). Bạn xem nếu được mình squash, rebase rồi merge vô master nhé. Sorry bạn vì mình làm mất thời gian bạn nhiều quá.

@tonyvugithub 
Hi anh! Anh rãnh và interest thì review qua document này giúp em. Em nhớ nah bảo đang tự học React, bài này relate được nhiều fundamental của React lắm!

2019-12-30 11:33 UTC, vitokhangnguyen approved these changes

2019-12-30 20:38 UTC, merged

2019-12-30 20:39 UTC, giatuongtran9 commented
@vitokhangnguyen sorry mình chưa đọc comment mà merge luôn rồi..

2019-12-30 20:40 UTC, giatuongtran9 commented
@vitokhangnguyen bạn có thể reset master để mình rebasel lại không?

2019-12-30 22:39 UTC, vitokhangnguyen commented
Bên Gatsby họ khó master từ đầu rồi bạn, mình muốn chỉnh sửa gì cũng phải qua PR thôi. Không sao đâu bạn, lỡ rồi thôi vậy.